# Imagen base ligera
FROM debian:stable-slim

# Actualizar e instalar dependencias
RUN apt-get update && apt-get install -y \
    build-essential \
    libreadline-dev \
    git \
    valgrind \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Carpeta donde se copiará el proyecto
WORKDIR /minishell

# Copiar todos los archivos del proyecto al contenedor
COPY . .

